// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS_VwLfb6LHJIbmIxCJhTbwikBX8E8rQM',
    appId: '1:873030490546:web:a07b0d34eda59249052cab',
    messagingSenderId: '873030490546',
    projectId: 'chat-38d0a',
    authDomain: 'chat-38d0a.firebaseapp.com',
    storageBucket: 'chat-38d0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUlj9GI0vC1cNS7yK6_Jk70PzMUE8BtA',
    appId: '1:873030490546:android:b55cdfee37c92151052cab',
    messagingSenderId: '873030490546',
    projectId: 'chat-38d0a',
    storageBucket: 'chat-38d0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0QqWP50TRIfDPLeJ5fWlB7nTlQAeXpi0',
    appId: '1:873030490546:ios:ba17ea9f23e3eb83052cab',
    messagingSenderId: '873030490546',
    projectId: 'chat-38d0a',
    storageBucket: 'chat-38d0a.appspot.com',
    androidClientId: '873030490546-2qkcrgbgegvdl30igpja8r2v9ti21sk6.apps.googleusercontent.com',
    iosClientId: '873030490546-oamsbonc33f4kaanm2t209r7l3gbgbs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS_VwLfb6LHJIbmIxCJhTbwikBX8E8rQM',
    appId: '1:873030490546:web:82a215bd837f1458052cab',
    messagingSenderId: '873030490546',
    projectId: 'chat-38d0a',
    authDomain: 'chat-38d0a.firebaseapp.com',
    storageBucket: 'chat-38d0a.appspot.com',
  );
}